name: store_controller
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5

  shared_preferences: ^2.2.3

  lottie: ^3.1.0

  connectivity_plus: ^6.0.5


  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: any
  go_router: any
  http: any
  intl: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1



flutter:
  uses-material-design: true
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900


  assets:
    - assets/icon/wolf.png
    - assets/icon/header_icon.png




flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/icon/apps_icon.png

